using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
 * What is the value of the first triangle number to have over five hundred divisors? */

namespace Puzzle_9
{
    class Program
    {
        static void Main(string[] args)
        {
            int i = 1, sum = 0, chk;

            do
            {
                sum = sum + i;
                chk = factors(sum);
                if (chk > 500)
                {
                    Console.WriteLine("the triangle number is {0}", sum);
                    break;
                }
                i++;

            }
            while (i != 0);
            Console.ReadKey();

            int factors(int num)
            {
                int cnt = 2, j = 2;
                while(j*j <= sum)
                {
                    if(sum % j==0)
                    {
                        if (sum == j * j)
                        {
                            cnt++;
                        }
                        else

                        cnt += 2;
                    }
                    j++;
                }
                return cnt;
            }
        }
    }
}
